### ISSUE TITLE
Not working with bulkCreate

### ISSUE THREAD

**Issue by fnematov** [jarrodconnolly/sequelize-slugify#20]
hi, I use like this
`let slugify = require('sequelize-slugify');`
```
slugify.slugifyModel(Nomenclatures, {
        source: ['name'],
        slugOptions: { lower: true },
        overwrite: false,
        column: 'slug'
    });
```
In my case slug can not be null
`await model.bulkCreate(json_data);`

It gives me an error slug can not be null

**Comment by jarrodconnolly** [comment]
`bulkCreate()` should be working, there is a unit test as of #51 
https://github.com/jarrodconnolly/sequelize-slugify/blob/main/jest-tests/slug-bulk-update.test.js
