### ISSUE TITLE
Don't work beforeUpdate

### ISSUE THREAD

**Issue by ikloster03** [jarrodconnolly/sequelize-slugify#21]
Hello, I've found a problem. The hook beforeUpdate don't work for [model's method update](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-update). I.e. slug's col doesn't update with name.
e.g.:

```javascript
await Person.update(
    {
      name: name,
      description: description
    },
    { where: { id: id } }
  )
```

But if I use this code:

```javascript
  const person = await Person.findByPk(id)
  await person.update({
    name: name,
    description: description
  })
```
Everything works well.

**Comment by jarrodconnolly** [comment]
This is interesting as it seems there is a difference in how hooks behave in those two situations.

http://docs.sequelizejs.com/manual/hooks.html#instance-hooks

We may be able to hook the `beforeBulkUpdate` and see how that works but it will take some testing. It also looks like you would be able to pass the option

**Comment by jarrodconnolly** [comment]
On closer look, the warning about memory usage while using the `individualHooks` probably makes it a bad idea. I will look into supporting the `beforeBulk*` methods properly.

This may also help with issue #20

**Comment by jarrodconnolly** [comment]
Release v1.5.0 has a new option to automatically enable `individualHooks` when doing a bulk update using the Model.update() method.
