### ISSUE TITLE
Cannot update the slug when the title is changed

### ISSUE THREAD

**Issue by Hervera** [jarrodconnolly/sequelize-slugify#31]
The slug must also gets updated when the title is changed

**Comment by jarrodconnolly** [comment]
Can you give an example of where this is not working? 
Is the title field setup correctly as a source for the slug?

Thank you for the report, a little more information will be needed to investigate.

**Comment by sum4li** [comment]
hello there. thank you for the great job. i think i have the same problem here
here it is my code
`import db from '../../../config/database'
import sequelize_slugify from 'sequelize-slugify';

let sequelize = db.sequelize
let DataTypes = db.Sequelize

const model = sequelize.define('mst_product_tags', {
    tag_id: {
        type: DataTypes.BIGINT,
        primaryKey: true,
        autoIncrement: true,
        field: 'tag_id',
        unique: true,
        allowNull: false 
    },
    tag_name: {
        type: DataTypes.STRING(191),
        field: 'tag_name',
        unique: true,
        allowNull: false
    },
    tag_slug: {
        type: DataTypes.STRING(191),
        field: 'tag_slug',
        unique: true
    },    
    created_by: {
        type: DataTypes.STRING(45),
        field: 'created_by',
        allowNull: true
    },
    updated_by: {
        type: DataTypes.STRING(45),
        field: 'updated_by',
        allowNull: true
    }
}, {
    tableName: 'mst_product_tags',
    timestamps: true,
    underscored: true
})
model.removeAttribute('id')

sequelize_slugify.slugifyModel(model,{
    source: ['tag_name'],
    overwrite: true,
    column: 'tag_slug'
});

module.exports = model`

when im update "tag_name" then "tag_slug" doesnt change. can you help me. thank you

**Comment by Limerin555** [comment]
Yes, currently experiencing the same issue here.

I have this in my model :
`SequelizeSlugify.slugifyModel(Blog, {
    source: ['subject'],
    suffixSource: ['timestamp'],
    slugOptions: { lower: true },
    overwrite: true,
    column: 'slug',
    incrementalReplacement: '-'
  });`

It works fine if I'm creating a new entry but it doesn't update the "slug" column whenever the "subject" column is updated.

**Comment by Limerin555** [comment]
Yes, currently experiencing the same issue here.

I have this in my model :

    SequelizeSlugify.slugifyModel(Blog, {
        source: ['subject'],
        suffixSource: ['timestamp'],
        slugOptions: { lower: true },
        overwrite: true,
        column: 'slug',
        incrementalReplacement: '-'
    });

It works fine if I'm creating a new entry but it doesn't update the "slug" column whenever the "subject" column is updated.

**Comment by jarrodconnolly** [comment]
Thank you for providing details to your use case and issue. I will look into this issue closer.

**Comment by jarrodconnolly** [comment]
@Limerin555 It would be great to see the code you are using to modify the subject column. That would greatly help to narrow down where the issue lies.

**Comment by mromiario** [comment]
Hi, I have the same issue too. But when I'm trying to update the data by instance method like this, it works well. Maybe you can try it @Limerin555 @sum4li and maybe it will give you a hint @jarrodconnolly 

```
  const contentObj = await content.findOne({ where: { id } })
  await contentObj.update(
      {
        title,
        content_body,
        description,
        content_status_id,
        thumbnail_photo
      }
    )
```

**Comment by BenPilliez** [comment]
Hi @mromiario, @Limerin555, @sum4li you can use beforeUpdate hook    
category.init({
        name: {type: DataTypes.STRING, allowNull: false, unique: {args: true, msg: "Une catégorie existe déjà avec ce nom"}},
        slug: {type: DataTypes.STRING, unique: true},
        createdAt: {
            type: DataTypes.DATE,
            allowNull: false,
            defaultValue: sequelize.NOW
        },
        updatedAt: {
            type: DataTypes.DATE,
            allowNull: false,
            defaultValue: sequelize.NOW
        }
    }, {
        hooks:{
            beforeUpdate(instance, options) {
                SequelizeSlugify.slugifyModel(category, {
                    source: ['name']
                })
            }
        },
        sequelize,
        modelName: 'category',
    });

**Comment by jarrodconnolly** [comment]
I believe this was an issue related to using the Model.update() bulk update method instead of on individual instances.

Release v1.5.0 has a new option to automatically enable `individualHooks` when doing a bulk update using the Model.update() method.

**Comment by hieuhuynh93** [comment]
@jarrodconnolly Hello, I got the same issue. Here is my model:
`SequelizeSlugify.slugifyModel(Stores, {
      source: ['storeName'],
      slugOptions: { lower: true },
      overwrite: true,
      column: 'storeSlug',
      incrementalSeparator: '-',
      passTransaction: true,
      paranoid: true
    });`

And here is my update data code
`await db.stores.update(storeData,{where: {storeId: storeId}})`

**Comment by shivraj-geekologix** [comment]
> I believe this was an issue related to using the Model.update() bulk update method instead of on individual instances.
> 
> Release v1.5.0 has a new option to automatically enable `individualHooks` when doing a bulk update using the Model.update() method.

Still getting the same slug, it is not updating after changing the title.
