### ISSUE TITLE
Slug replacement for incremental counter

### ISSUE THREAD

**Issue by bossyan** [jarrodconnolly/sequelize-slugify#34]
When we specify `replacement` in the `slugOptions`, it only replaces within the slug and not the incremental counter.

Example I used to slugify a model:

```
SequelizeSlugify.slugifyModel(People, {
    source: ['first_name', 'last_name'],
    slugOptions: {
        replacement: '_'
    },
    overwrite: false,
    column: 'identifier'
});
```

This will generate `first_last`. If it already exist, it will generate `first_last-1`.

I'd like to replace the separator for the counter to `first_last_1`, `first_last_2`, etc..

**Comment by jarrodconnolly** [comment]
Interesting, I have not seen a request for this. I am open to a PR allowing an optional separator for the counter. As long as it defaults to - and maintains backward compatibility with default settings that should be fine.
Thank you for bringing up this issue.

**Comment by bossyan** [comment]
Done. Please review it and let me know what you think. Thanks

**Comment by bossyan** [comment]
Can you review this and approve if it looks good? @jarrodconnolly

**Comment by jarrodconnolly** [comment]
Great work, thank you for the unit tests.
