### ISSUE TITLE
Slug is not updating even after changing the title.

### ISSUE THREAD

**Issue by shivraj-geekologix** [jarrodconnolly/sequelize-slugify#58]

**Comment by jarrodconnolly** [comment]
Thank you for the report. If you could add some details like what database you are using and an example reproduction that would go a long way.

**Comment by jarrodconnolly** [comment]
Ahh, I see you also commented on issue #31 
I will think about the issue in relation to that older problem.

**Comment by jarrodconnolly** [comment]
For now, the test that shows the use of `individualHooks` that went along to solve #31 is here, maybe something there will help you.

https://github.com/jarrodconnolly/sequelize-slugify/blob/e6a299ed64c2b3dc2670ed75dc1f10cd53a3394a/jest-tests/slug-bulk-update.test.js#L41

**Comment by shivraj-geekologix** [comment]
Now I have added "bulkUpdate: true", It is working fine. Like this
```
  SequelizeSlugify.slugifyModel(Brand, {
    source: ['name'],
    bulkUpdate: true
  });
```

But without adding "bulkUpdate: true", it is not updating the slug, Can you please elaborate that how "individualHooks" works?

Thanks
