### ISSUE TITLE
Documentation link is invalid

### ISSUE THREAD

**Issue by bhattisatish** [jarrodconnolly/sequelize-slugify#60]
* **Node.js**: All
* **OS**: All
* **Sequelize**: Current
* **Database**: All

### What steps will reproduce the bug?

The Readme.md has a link to documentation pointing to https://sequelize-slugify.nestedquotes.ca/ But the URL is invalid.

### How often does it reproduce? Is there a required condition?
NA
### What is the expected behavior?
The url should point to a valid location. Or better still point to the internal doc links: for [example](https://github.com/jarrodconnolly/sequelize-slugify/blob/main/docs/examples.md)

**Comment by jarrodconnolly** [comment]
Thank you for your report!

It is always DNS.

The site should be working again shortly, once DNS propagates.
