### ISSUE TITLE
transaction support?

### ISSUE THREAD

**Issue by thebigredgeek** [jarrodconnolly/sequelize-slugify#9]
It might be a good idea to pass `options.transaction` to `checkSlug`.  This plugin doesn't seem like it would be reliable for insertions of many records within a single transaction, since it doesn't scope the `Model.find` to the transaction.

**Comment by thebigredgeek** [comment]
https://github.com/jarrodconnolly/sequelize-slugify/pull/10

**Comment by jarrodconnolly** [comment]
Much appreciated! Functionality coming soon in the 1.x release.
